version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: &weekly
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 5
    groups: &minor-patch
      minor-and-patch:
        update-types: [minor, patch]
    labels: &labels [dependencies]
    commit-message: &commit
      prefix: chore(deps)

  - package-ecosystem: github-actions
    directory: /
    schedule: *weekly
    open-pull-requests-limit: 5
    groups: *minor-patch
    labels: *labels
    commit-message: *commit
