name: Improvement
description: Refinement that improves ergonomics, clarity, or operability
title: ""
type: Improvement
body:
  - type: textarea
    id: problem
    attributes:
      label: Current problem
    validations:
      required: true
  - type: textarea
    id: improvement
    attributes:
      label: Proposed improvement
    validations:
      required: true

