services:
  ingester:
    image: signoz/signoz-otel-collector@sha256:f9bf94d566055d06581f3befbf361cc26d670f31ad00cb31fda2ec380210c5ec
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
        /signoz-otel-collector migrate sync check &&
        /signoz-otel-collector --config=/etc/otel-collector-config.yaml
    environment:
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN=tcp://signoz-telemetrystore-clickhouse-0-0:9000
      - SIGNOZ_OTEL_COLLECTOR_TIMEOUT=10m
    ports:
      - ${MESSAGING_RUNTIME_SIGNOZ_OTLP_GRPC_PORT:-14317}:4317
      - ${MESSAGING_RUNTIME_SIGNOZ_OTLP_HTTP_PORT:-14318}:4318
    restart: unless-stopped
    networks:
      signoz-network:
        aliases:
          - signoz-ingester
    volumes:
      - ./ingester/ingester.yaml:/etc/otel-collector-config.yaml:ro
      - ./ingester/opamp.yaml:/etc/opamp-config.yaml:ro

  signoz-metastore-postgres-0:
    image: postgres:16
    environment:
      - POSTGRES_DB=signoz
      - POSTGRES_PASSWORD=signoz
      - POSTGRES_USER=signoz
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U signoz -d signoz
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - signoz-network
    volumes:
      - signoz-metastore-postgres-0-data:/var/lib/postgresql/data

  signoz-signoz-0:
    image: signoz/signoz@sha256:0149e8119c9d0fbd457bb612f7aef4f162df2871184d8a0c450c9d536519dbce
    environment:
      - SIGNOZ_SQLSTORE_POSTGRES_DSN=postgres://signoz:signoz@signoz-metastore-postgres-0:5432/signoz?sslmode=disable
      - SIGNOZ_SQLSTORE_PROVIDER=postgres
      - SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN=tcp://signoz-telemetrystore-clickhouse-0-0:9000
      - SIGNOZ_TELEMETRYSTORE_PROVIDER=clickhouse
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -q
        - http://localhost:8080/api/v1/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    ports:
      - ${MESSAGING_RUNTIME_SIGNOZ_UI_PORT:-18080}:8080
    restart: unless-stopped
    networks:
      - signoz-network

  signoz-telemetrykeeper-clickhousekeeper-0:
    image: clickhouse/clickhouse-keeper:25.5.6
    environment:
      - KEEPER_CONFIG=/etc/clickhouse-keeper/keeper.yaml
    healthcheck:
      test:
        - CMD
        - clickhouse-keeper-client
        - -h
        - localhost
        - -p
        - "9181"
        - -q
        - ls
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - signoz-network
    volumes:
      - signoz-telemetrykeeper-0-data:/var/lib/clickhouse-keeper
      - ./telemetrykeeper/clickhousekeeper/keeper-0.yaml:/etc/clickhouse-keeper/keeper.yaml:ro

  signoz-telemetrystore-clickhouse-user-scripts:
    image: clickhouse/clickhouse-server:25.5.6
    command:
      - bash
      - -c
      - |
        version="v0.0.1"
        node_os=$$(uname -s | tr '[:upper:]' '[:lower:]')
        node_arch=$$(uname -m | sed s/aarch64/arm64/ | sed s/x86_64/amd64/)
        echo "Fetching histogram-binary for $${node_os}/$${node_arch}"
        cd /tmp
        wget -O histogram-quantile.tar.gz "https://github.com/SigNoz/signoz/releases/download/histogram-quantile%2F$${version}/histogram-quantile_$${node_os}_$${node_arch}.tar.gz"
        tar -xvzf histogram-quantile.tar.gz
        mv histogram-quantile /var/lib/clickhouse/user_scripts/histogramQuantile
    restart: on-failure
    networks:
      - signoz-network
    volumes:
      - signoz-telemetrystore-user-scripts:/var/lib/clickhouse/user_scripts

  signoz-telemetrystore-clickhouse-0-0:
    image: clickhouse/clickhouse-server:25.5.6
    depends_on:
      signoz-telemetrykeeper-clickhousekeeper-0:
        condition: service_healthy
      signoz-telemetrystore-clickhouse-user-scripts:
        condition: service_completed_successfully
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
      - CLICKHOUSE_CONFIG=/etc/clickhouse-server/config.yaml
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -q
        - http://localhost:8123/ping
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - signoz-network
    volumes:
      - signoz-telemetrystore-0-0-data:/var/lib/clickhouse
      - signoz-telemetrystore-user-scripts:/var/lib/clickhouse/user_scripts:ro
      - ./telemetrystore/clickhouse/config-0-0.yaml:/etc/clickhouse-server/config.yaml:ro
      - ./telemetrystore/clickhouse/functions.yaml:/etc/clickhouse-server/functions.yaml:ro

  signoz-telemetrystore-migrator:
    image: signoz/signoz-otel-collector@sha256:f9bf94d566055d06581f3befbf361cc26d670f31ad00cb31fda2ec380210c5ec
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
        /signoz-otel-collector migrate ready &&
        /signoz-otel-collector migrate bootstrap &&
        /signoz-otel-collector migrate sync up &&
        /signoz-otel-collector migrate async up
    environment:
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN=tcp://signoz-telemetrystore-clickhouse-0-0:9000
      - SIGNOZ_OTEL_COLLECTOR_TIMEOUT=10m
    restart: on-failure
    networks:
      - signoz-network

networks:
  signoz-network:

volumes:
  signoz-metastore-postgres-0-data:
  signoz-telemetrykeeper-0-data:
  signoz-telemetrystore-0-0-data:
  signoz-telemetrystore-user-scripts:
